messagebird/csharp-rest-api

MessageBird/Objects/Message.cs

Add the 'auto' option to the DataEncoding enum

---

Examples/Verify/CreateVoiceVerify.cs
MessageBird/Client.cs
MessageBird/Objects/Message.cs
MessageBird/Utilities/Validation.cs

changed messagetype Enum to support TTS
added verify example with voicemessage

added posibility for messagetype TTS (voice) for verify method

---

MessageBird/MessageBird.csproj.nuspec

The package now targets both .NET Framework 4.0 and .NET Standard 2.0.

Prepare nuspec for releasing a multi-target package.

---

MessageBird/MessageBird.csproj
MessageBird/MessageBird.csproj.nuspec
MessageBird/Net/RestClient.cs

This version adds support for .NET Standard 2.0.

Bump version to 1.3.7.

---

MessageBird/MessageBird.csproj
MessageBird/MessageBird.csproj.nuspec
MessageBird/Net/RestClient.cs

Adds support for contacts and groups.

Bump version to 1.4.0.

---

MessageBird/MessageBird.csproj
MessageBird/MessageBird.csproj.nuspec
MessageBird/Net/RestClient.cs

Client now has an explicit dependency on  the `Newonsoft.Json` NuGet package. Version `>= 9.0.1`.

Support newtonsoft json 901

---

MessageBird/MessageBird.csproj
MessageBird/MessageBird.csproj.nuspec
MessageBird/Net/RestClient.cs
MessageBird/Objects/Request.cs
MessageBird/RequestSigner.cs
Tests/UnitTests/MessageBirdUnitTests/MessageBirdUnitTests.csproj
Tests/UnitTests/MessageBirdUnitTests/Resources/RequestSignerTest.cs

Completely ported from java library.
I think tests are enough for usage demonstration, aren't they?

Add request signer for messagebird webhook verification

---

MessageBird/MessageBird.csproj
MessageBird/MessageBird.csproj.nuspec
MessageBird/Net/RestClient.cs

The new release includes support for the Conversations API

Bump SDK version to 1.6.0.0.

---

MessageBird/Client.cs
MessageBird/ConversationsClient.cs
MessageBird/Resources/Conversations/Contacts.cs
MessageBird/Resources/Conversations/ConversationLists.cs
MessageBird/Resources/Conversations/ConversationStart.cs
MessageBird/Resources/Conversations/Conversations.cs
MessageBird/Resources/Conversations/ConversationsBaseLists.cs
MessageBird/Resources/Conversations/ConversationsResource.cs
MessageBird/Resources/Conversations/MessageLists.cs
MessageBird/Resources/Conversations/MessageSend.cs
MessageBird/Resources/Conversations/Messages.cs
MessageBird/Resources/Conversations/WebhookLists.cs
MessageBird/Resources/Conversations/Webhooks.cs
MessageBird/Resources/Resource.cs
README.md
Tests/UnitTests/MessageBirdUnitTests/Resources/ConversationTest.cs

GROW-584
DASH-8197
Added a flag to enable access to WhatsApp Sandbox for Conversations API

Add WhatsApp Sandbox support to Conversations API

---

Examples/Examples.csproj
Examples/Webhooks/CreateWebhook.cs
Examples/Webhooks/DeleteWebhook.cs
Examples/Webhooks/ListWebhooks.cs
Examples/Webhooks/UpdateWebhook.cs
Examples/Webhooks/ViewWebhook.cs
MessageBird/Client.cs
MessageBird/Objects/Voice/Webhook.cs
MessageBird/Resources/Voice/WebhookLists.cs
MessageBird/Resources/Voice/Webhooks.cs
Tests/UnitTests/MessageBirdUnitTests/MessageBirdUnitTests.csproj
Tests/UnitTests/MessageBirdUnitTests/Resources/WebhookTest.cs
Tests/UnitTests/MessageBirdUnitTests/Responses/WebhooksCreate.json
Tests/UnitTests/MessageBirdUnitTests/Responses/WebhooksList.json
Tests/UnitTests/MessageBirdUnitTests/Responses/WebhooksUpdate.json
Tests/UnitTests/MessageBirdUnitTests/Responses/WebhooksView.json

Created the following CRUD operations for the Webhooks API:
* Create a webhook
* List all webhooks
* Viewing a webhook
* Updating a webhook
* Deleting a webhook

Added support for Webhooks in the SDK.

---

Examples/Transcriptions/CreateTranscription.cs
Examples/Transcriptions/DownloadTranscription.cs
Examples/Transcriptions/ListTranscriptions.cs
Examples/Transcriptions/ViewTranscription.cs
MessageBird/Client.cs
MessageBird/Objects/Voice/Transcription.cs
MessageBird/Resources/Voice/Transcriptions.cs
MessageBird/Resources/Voice/TranscriptionsLists.cs
Tests/UnitTests/MessageBirdUnitTests/Resources/TranscriptionTest.cs
Tests/UnitTests/MessageBirdUnitTests/Responses/TranscriptionCreate.json
Tests/UnitTests/MessageBirdUnitTests/Responses/TranscriptionList.json
Tests/UnitTests/MessageBirdUnitTests/Responses/TranscriptionView.json

Requests implemented:
- Create transcription
- List transcriptions
- View transcription
- Download transcription

Added support for Voice API Transcriptions requests

---

.gitignore
MessageBird/Client.cs
MessageBird/Objects/Voice/VoiceBaseList.cs
MessageBird/Resources/Voice/VoiceBaseLists.cs
Tests/UnitTests/MessageBirdUnitTests/Resources/CallFlowTest.cs
Tests/UnitTests/MessageBirdUnitTests/Resources/CallTest.cs
Tests/UnitTests/MessageBirdUnitTests/Resources/RecordingTest.cs

Changes:
- Fixed pagination for Voice API by replacing `offset` with `page`
- Updated **.gitignore** for Mac **.DS_Store** files

Voice API: fixed pagination

---

MessageBird/Client.cs
Tests/UnitTests/MessageBirdUnitTests/Resources/TranscriptionTest.cs
Tests/UnitTests/MessageBirdUnitTests/Resources/WebhookTest.cs

- Replaced incorrect `offset` references with `page`
- Fixed tests

Fix master: replace offset with page

---

Examples/VoiceMessage/ListVoiceMessages.cs
MessageBird/Client.cs
MessageBird/Objects/VoiceMessageList.cs
MessageBird/Resources/VoiceMessageList.cs
Tests/UnitTests/MessageBirdUnitTests/Resources/VoiceMessageTest.cs
Tests/UnitTests/MessageBirdUnitTests/Responses/ListVoiceMessages.json

List voice messages method

---

MessageBird/Objects/Conversations/MediaContent.cs

Caption property is missing in MediaContent property.

Added caption to MediaContent

---

MessageBird/Objects/Conversations/Content.cs

Solves deserialization issue for event content type

---

Examples/Message/SendTemplatedMessage.cs

Added WhatsApp HSM - templated message example

WhatsApp HSM - sending templated message

---

MessageBird/Objects/Recipient.cs

Add Recipient MessagePartCount property

Add MessageCountPart to Recipient object

---

Examples/Call/CreateCall.cs
Examples/CallFlow/CreateCallFlow.cs
Examples/CallFlow/ListCallFlow.cs
Examples/CallFlow/UpdateCallFlow.cs
Examples/CallFlow/ViewCallFlow.cs
MessageBird/Client.cs
Tests/UnitTests/MessageBirdUnitTests/Resources/CallFlowTest.cs
Tests/UnitTests/MessageBirdUnitTests/Resources/CallTest.cs
Tests/UnitTests/MessageBirdUnitTests/Responses/CallFlowList.json

This field is deprecated now although users still can send and receive it.

Deprecate CallFlow Title usage

---

MessageBird/Objects/Common/Enums.cs
Tests/UnitTests/MessageBirdUnitTests/Resources/ClientVerifyTest.cs

This issue: https://github.com/messagebird/csharp-rest-api/issues/118 I have created the necessary Enum values. Also I fixed the typo in Portuguese.

Added languages according to MB frontend
